### ISSUE TITLE
I'm getting an error

### ISSUE THREAD

**Issue by 2534905003** [AuroraNetworkStudios/Aurora#2]
I've run into an error, and so far I haven't found it affecting the content in the game, but it keeps outputting the error

[16:52:57] [Region Scheduler Thread #5/WARN]: [Aurora] Location task for Aurora v2.1.0 in world CraftWorld{name=world} at 69, -90 generated an exception
java.lang.IllegalStateException: World mismatch: expected world_the_end but got world
	at net.minecraft.world.level.Level.getCurrentWorldData(Level.java:694) ~[luminol-1.21.1.jar:1.21.1-DEV-791d374]
	at net.minecraft.world.level.Level.getBlockState(Level.java:1311) ~[luminol-1.21.1.jar:1.21.1-DEV-791d374]
	at org.bukkit.craftbukkit.block.CraftBlock.getType(CraftBlock.java:244) ~[luminol-1.21.1.jar:1.21.1-DEV-791d374]
	at [A][任务前置]Aurora-2.1.0.jar/gg.auroramc.aurora.expansions.region.RegionBlockListener.lambda$onSandFall$0(RegionBlockListener.java:59) ~[[A][任务前置]Aurora-2.1.0.jar:?]
	at io.papermc.paper.threadedregions.scheduler.FoliaRegionScheduler$LocationScheduledTask.run(FoliaRegionScheduler.java:331) ~[luminol-1.21.1.jar:?]
	at io.papermc.paper.threadedregions.scheduler.FoliaRegionScheduler$Scheduler.tick(FoliaRegionScheduler.java:272) ~[luminol-1.21.1.jar:?]
	at io.papermc.paper.threadedregions.scheduler.FoliaRegionScheduler.tick(FoliaRegionScheduler.java:142) ~[luminol-1.21.1.jar:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1699) ~[luminol-1.21.1.jar:1.21.1-DEV-791d374]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:407) ~[luminol-1.21.1.jar:1.21.1-DEV-791d374]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:459) ~[luminol-1.21.1.jar:1.21.1-DEV-791d374]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:546) ~[luminol-1.21.1.jar:1.21.1-DEV-791d374]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by ErikSzabo** [comment]
Can you reproduce this on folia?

**Comment by 2534905003** [comment]
> 你能在 folia 上复制这个吗？

Yes, I have a plugin running on a folia's fork, LuminolMC

是的，我在folia的一个fork,LuminolMC运行的插件

**Comment by ErikSzabo** [comment]
Luminol is not folia. It is a fork of folia.

**Comment by 2534905003** [comment]
I'm sorry, my English is not good and I have a problem with my expression, so can you help me solve this error

**Comment by ErikSzabo** [comment]
Luminol and other potentionally unstable folia forks are not supported. Only base folia is supported. Though your error probably comes from a fact that an enderman picks up a player placed sand/gravel block and then teleports into another world. This won’t effect gameplay ever and you can safely ignore the error. This is probably not fixable without removing the check for it, but since it works fine on paper servers, it is not a top priority thing for now.

**Comment by 2534905003** [comment]
Ok thank you

**Comment by 2534905003** [comment]
I'm bothering you again.,This error swipes the screen.,20 minutes and 1GB log appeared.,Can I block it.

**Comment by ErikSzabo** [comment]
Try latest dev build
https://auroramc.gg/downloads/aurora

**Comment by 2534905003** [comment]
Still having this problem
[22:30:36] [Region Scheduler Thread #14/WARN]: [Aurora] Location task for Aurora v2.1.1 in world CraftWorld{name=world} at -1376, 542 generated an exception
java.lang.IllegalStateException: World mismatch: expected world_the_end but got world
	at net.minecraft.world.level.Level.getCurrentWorldData(Level.java:694) ~[luminol-1.21.1.jar:1.21.1-DEV-791d374]
	at net.minecraft.world.level.Level.getBlockState(Level.java:1311) ~[luminol-1.21.1.jar:1.21.1-DEV-791d374]
	at org.bukkit.craftbukkit.block.CraftBlock.getType(CraftBlock.java:244) ~[luminol-1.21.1.jar:1.21.1-DEV-791d374]
	at [A][任务前置]Aurora-2.1.1.jar/gg.auroramc.aurora.expansions.region.RegionBlockListener.lambda$onSandFall$0(RegionBlockListener.java:62) ~[[A][任务前置]Aurora-2.1.1.jar:?]
	at io.papermc.paper.threadedregions.scheduler.FoliaRegionScheduler$LocationScheduledTask.run(FoliaRegionScheduler.java:331) ~[luminol-1.21.1.jar:?]
	at io.papermc.paper.threadedregions.scheduler.FoliaRegionScheduler$Scheduler.tick(FoliaRegionScheduler.java:272) ~[luminol-1.21.1.jar:?]
	at io.papermc.paper.threadedregions.scheduler.FoliaRegionScheduler.tick(FoliaRegionScheduler.java:142) ~[luminol-1.21.1.jar:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1699) ~[luminol-1.21.1.jar:1.21.1-DEV-791d374]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:407) ~[luminol-1.21.1.jar:1.21.1-DEV-791d374]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:459) ~[luminol-1.21.1.jar:1.21.1-DEV-791d374]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:546) ~[luminol-1.21.1.jar:1.21.1-DEV-791d374]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by ErikSzabo** [comment]
Well if your falling blocks are not falling from the world to world_the_end, it is probably a luminol issue. Try reproduce it on base folia and send more details what happens in game.

**Comment by 2534905003** [comment]
> Well if your falling blocks are not falling from the world to world_the_end, it is probably a luminol issue. Try reproduce it on base folia and send more details what happens in game.

It could be that the sand fell from the word through the portal to world_the_end

**Comment by ErikSzabo** [comment]
Now at least we know now how to reproduce the issue. I will fix it later.

**Comment by ErikSzabo** [comment]
Should be fixed now.
https://modrinth.com/plugin/auroralib/version/2.1.1

**Comment by 2534905003** [comment]
> 现在应该修复。 https://modrinth.com/plugin/auroralib/version/2.1.1

I changed the plugin with the new version number and continued to observe it for a while. Thank you for the active maintenance of the plugin, yesterday this error wrote 45 GB of memory on the server's logs

**Comment by ErikSzabo** [comment]
> > 现在应该修复。 https://modrinth.com/plugin/auroralib/version/2.1.1
> 
> 
> 
> I changed the plugin with the new version number and continued to observe it for a while. Thank you for the active maintenance of the plugin, yesterday this error wrote 45 GB of memory on the server's logs

The event handler now doesn't do anything on folia.
